name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  landme:
    if: github.event.label.name == 'merge-me'

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
￼    - uses: actions/checkout@v2
#       with:
#         ref: '' XXX FIXME

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}
￼
