name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  merge-me:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Check git situation
      if: github.event.label.name == 'merge-me'
      run: |
        pwd
        git remote -v

    - name: Attempt merge
      if: github.event.label.name == 'merge-me'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/workflows/script.bash

