name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  merge-me:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Dump GitHub context
      if: github.event.label.name == 'merge-me'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: bash .github/workflows/script.bash

