name: Merge PRs

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history

    - name: Configure git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Attempt merges
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: go run gha.go
